fae_paths/fae_paths/urls.py
from django.contrib import admin
from django.urls import path, include
from fae_paths_app.views import home

# Url patterns for fae_paths
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fae_paths_app.urls')),
    path('user_auth', include('user_auth.urls')),
]

fae_paths/fae_paths_app/urls.py
from django.urls import path, include
from .views import home, SpellListView
from . import views

# Define a URL pattern for the home page.
# Define a URL pattern for a list of spells.
# Define a URL pattern for a character gallery.
# Define a URL pattern for user auth.
urlpatterns = [
    path('', home, name='home'),
    path('spell-list/', SpellListView.as_view(), name='spell_list'),
    path('character_gal/', views.character_gallery, name='character_gallery'),
    path('user_auth/', include('user_auth.urls')),

]

fae_paths/user_auth/urls.py
from django.urls import path
from . import views

app_name = 'user_auth'

# URL patterns for the 'user_auth' app
urlpatterns = [
    path('', views.user_login, name='login'),
    path('authenticate_user/', views.authenticate_user, name='authenticate_user'),
    path('show_user/', views.show_user, name='show_user'),
    path('register/', views.register, name='register'),
]

fae_paths/fae_paths_app/models.py
from django.db import models

# Create your models here.
class Meta:
    app_label = 'fae_paths'

# Define a model for representing Spells.
class Spell(models.Model):
    # Field to store the name of the spell (limited to 100 characters).
    name = models.CharField(max_length=100)

    # Field to store the description of the spell (text field for longer descriptions).
    description = models.TextField()

    # A human-readable representation of a Spell object.
    def __str__(self):
        return self.name

# Define a model for representing Characters.
class Character(models.Model):
    # Field to store the name of the character (limited to 100 characters).
    name = models.CharField(max_length=100)

    # Field to store the image path of the character (limited to 255 characters).
    image_path = models.CharField(max_length=255)

    # A human-readable representation of a Character object.
    def __str__(self):
        return self.name

fae_paths/user_auth/models.py
from django.db import models

# Create your models here.

fae_paths/fae_paths_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Spell
from .models import Character
from django.contrib.auth.decorators import login_required

# Define a view function for the home page.
def home(request):
    # Render the 'home.html' template.
    return render(request, 'fae_paths_app/home.html')

# Define a class-based view for listing spells.
class SpellListView(ListView):
    model = Spell
    template_name = 'fae_paths_app/spell_list.html'
    context_object_name = 'spells'

@login_required(login_url="/user_auth")  # Add the login_required decorator
def character_gallery(request):
    characters = Character.objects.all()
    return render(request, 'fae_paths_app/character_gal.html', {'characters': characters})

fae_paths/user_auth/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse

def user_login(request):
    """
    Render the login page.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Rendered login page.
    """
    return render(request, 'authentication/login.html')

def authenticate_user(request):
    """
    Authenticate a user based on the provided credentials.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponseRedirect: Redirects to the login page upon successful authentication,
                             otherwise redirects back to the login page.
    """
    if request.method == 'POST':
        username = request.POST.get('username') 
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('user_auth:login'))
        else:
            return redirect('user_auth:login')

def show_user(request):
    """
    Display user information.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Rendered user information page.
    """
    return render(request, 'authentication/user.html', {
        "username": request.user.username,
        "password": request.user.password 
    })

def register(request):
    """
    Handle user registration.

    Args:
        request: The HTTP request object.

    Returns:
        HttpResponse: Rendered registration page or redirects to the login page upon successful registration.
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, f'Your account has been created. You can log in now!')    
            return HttpResponseRedirect(reverse('user_auth:login'))
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'registration/register.html', context)

fae_paths/fae_paths_app/templates/fae_paths_app/character_gal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fae Paths - Character Gallery</title>
    <link rel="stylesheet" href="{% static 'fae_paths_app/charstyle.css' %}">
</head>
<body>
    <div class="header">
        <h1>Fae Paths</h1>
    </div>
    
    <nav>
        <a href="/">Home</a>
        <a href="/spell-list">Spell List</a>
        <a href="/character_gal">Character Gallery</a>
    </nav>

    <div class="container">
        <center><h1>Characters - Deities</h1></center>
        <div class="Characters">
            <div class="realm">
                <h1>Gehenna, the Infernal Realm</h1>
                <!-- King Paimon, pantheon and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/paimon.jpg' %}" alt="King Paimon">
                    <h3>King Paimon</h3>
                    <h4>Abrahamic Pantheon</h4>
                    <p>King of Hell, Love, Chaos, and Art</p>
                </div>

                <!-- Mother Hekate, pantheon and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/hekate.jpg' %}" alt="Mother Hekate">
                    <h3>Mother Hekate</h3>
                    <h4>Greek Pantheon</h4>
                    <p>Goddess of Witchcraft, the Heavens, Earth, and Seas</p>
                </div>

                <!-- Kali Maa, pantheon and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/kali.jpg' %}" alt="Kali Maa">
                    <h3>Kali Maa</h3>
                    <h4>Hindu Pantheon</h4>
                    <p>Mother of Destruction and Death</p>
                </div>
            </div>

            <div class="realm">
                <h1>Nyad, the Water Realm</h1>
                <!-- Neptune, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/nep.jpg' %}" alt="Neptune">
                    <h3>Neptune</h3>
                    <h4>Roman Pantheon</h4>
                    <p>Ruler of the Seas</p>
                </div>

                <!-- Mazu, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/mazu.jpg' %}" alt="Mazu">
                    <h3>Mazu</h3>
                    <h4>Chinese Pantheon</h4>
                    <p>Goddess of the Sea and Protector of Sailors</p>
                </div>

                <!-- Chalchiuhtlicue, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/chal.jpg' %}" alt="Chalchiuhtlicue">
                    <h3>Chalchiuhtlicue</h3>
                    <h4>Aztec Pantheon</h4>
                    <p>Goddess of Water, Rivers, and Lakes</p>
                </div>
            </div>

            <div class="realm">
                <h1>Gaia, the Earth Realm</h1>
                <!-- Mahi'a, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/mahia.jpg' %}" alt="Mahi'a">
                    <h3>Mahi'a</h3>
                    <h4>Hawaiian Pantheon</h4>
                    <p>Goddess of Fertility and Growth</p>
                </div>

                <!-- Geb, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/geb.jpg' %}" alt="Geb">
                    <h3>Geb</h3>
                    <h4>Egyptian Pantheon</h4>
                    <p>God of the Earth and Vegetation</p>
                </div>

                <!-- Pachamama, pantheon, and desc -->
                <div class="deity">
                    <img src="{% static 'fae_paths_app/images/pach.jpg' %}" alt="Pachamama">
                    <h3>Pachamama</h3>
                    <h4>Incan Pantheon</h4>
                    <p>Goddess of the Earth and Time</p>
                </div>
            </div>
        </div>
    </div>
    
    <footer>
     <center><p>&copy; Fae Paths 2023</p></center>
    </footer>

</body>
</html>

fae_paths/fae_paths_app/templates/fae_paths_app/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fae Paths - Home</title>
    <link rel="stylesheet" href="{% static 'fae_paths_app/homestyle.css' %}">
</head>
<body>
    <div class="header">
        <h1>Fae Paths</h1>
    </div>

    <!-- Navigation bar -->
    <nav>
        <a href="/">Home</a>
        <a href="/spell-list">Spell List</a>
        <a href="/character_gal">Character Gallery</a>
    </nav>
    
    <div class="container">
        <!-- Home Page Content -->
        <center><img src="{% static 'fae_paths_app/images/cov.png' %}" alt="game cover" width="400" height="400"></center>
        <center><h2>Join the Fae Path</h2></center>
        <p> Embark on a mesmerizing journey into the mystical realms of "Fae Paths," a spellbinding fantasy video game that weaves together the tapestry of occultism and witchcraft. 
            In a world where ancient magicks collide, and the very essence of arcane knowledge is at stake, you will become the hero destined to save the multiverse from a malevolent force threatening to consume all forms of magick.
            
            <br/><br/>
            <b>Unleash the Power of the Occult:</b>
            Step into the shoes of a budding occultist, a master of arcane arts, capable of harnessing the most potent spells for healing, combat, and character enhancement. 
            Your journey begins with the mastery of essential spells, but as you progress, you'll delve deeper into the secrets of the craft, unlocking potent abilities to shape your destiny.
            
            <br/><br/>
            <b>Choose Your Companion:</b>
            As you venture forth, you'll have a crucial choice to make: Will you forge a bond with a mystical companion, a loyal familiar, or connect with the spirits of your ancestors? 
            Each choice brings unique advantages, guiding your path in unexpected ways. 
            A companion may offer combat support, a familiar might provide additional magical prowess, and an ancestor can impart wisdom from beyond the veil.
            
            <br/><br/>
            <b>Traverse Otherworldly Realms:</b>
            Travel through ancient portals to explore breathtaking and diverse realms, each with its own enchanting beauty and perilous challenges. 
            Encounter fae forests, ethereal sanctuaries, shadowy underworlds, and more, all brimming with secrets to uncover and creatures to face.
            
            <br/><br/>
            <b>Meet Deities of Myriad Pantheons:</b>
            As your quest unfolds, you will cross paths with deities from various pantheons, each holding a piece of the puzzle to unravel the greater evil threatening the very essence of magick. 
            Form alliances, seek their blessings, and unlock divine abilities to aid you in your battle against darkness.
            
            <br/><br/>
            <b>The Fate of Magick Hangs in the Balance:</b>
            A looming malevolence threatens to corrupt and obliterate all forms of magick across the realms. 
            To save the mystical arts and protect the balance of worlds, you must gather knowledge, forge alliances, and harness the full extent of your occult abilities. 
            Only by uniting the forces of light and mastering the Fae Paths can you hope to defeat the greater evil and ensure the survival of all you hold dear.
            
            <br/><br/>In "Fae Paths," your destiny as an occultist will unfold, leading you through a mesmerizing and perilous journey where the boundaries of magic blur, and the fate of multiple realms rests in your hands. 
            Are you ready to embrace the mystical and take your first step down the Fae Paths?</p>
    </div>
    
    <footer>
        <center><p>&copy; Fae Paths 2023</p></center>
    </footer>
    
</body>
</html>

fae_paths/fae_paths_app/templates/fae_paths_app/spell_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fae Paths - Spell List</title>
    <link rel="stylesheet" href="{% static 'fae_paths_app/spellstyle.css' %}">
</head>
<body>
    <div class="header">
        <h1>Fae Paths</h1>
    </div>
    
    <nav>
        <a href="/">Home</a>
        <a href="/spell-list">Spell List</a>
        <a href="/character_gal">Character Gallery</a>
    </nav>

    <div class="container">
        <center><h2>Spells</h2></center>
        <div class="spell-section">
            <!-- Spell 1 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/protect.png' %}" alt="Protection Spell">
                <h3>Protection Spell</h3>
                <p>Grants player invincibility from baneful attacks for 15 seconds</p>
            </div>

            <!-- Spell 2 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/luck.png' %}" alt="Luck Spell">
                <h3>Luck Spell</h3>
                <p>Grants player ability to skip 4 puzzles</p>
            </div>

            <!-- Spell 3 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/banish.png' %}" alt="Banishing Spell">
                <h3>Banishing Spell</h3>
                <p>When player visits the realm of infernals, firewalkers cannot touch them</p>
            </div>

            <!-- Spell 4 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/manip.png' %}" alt="Manipulation Spell">
                <h3>Manipulation Spell</h3>
                <p>Player is more charismatic or convincing</p>
            </div>

            <!-- Spell 5 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/invoke.png' %}" alt="Invocation Spell">
                <h3>Invocation Spell</h3>
                <p>Grants player the ability to call upon legion of spirits to fight with them, spirits abilities depend on the deity the player has built standing with</p>
            </div>

            <!-- Spell 6 -->
            <div class="spell">
                <img src="{% static 'fae_paths_app/images/oriah.png' %}" alt="Curse of Oriah">
                <h3>The curse of Oriah</h3>
                <p>Players drain enemies of all life force which activates rage and buffs for 10 seconds</p>
            </div>
        </div>
    </div>

    <footer>
        <center><p>&copy; Fae Paths 2023</p></center>
    </footer>

</body>
</html>

fae_paths/user_auth/templates/authentication/login.html
<h1> Login as User </h1>

<form action="{% url 'user_auth:authenticate_user' %}" method="post">
{% csrf_token %}

    <label>Username</label>
    <input type="text" name="username" placeholder="User" required>
    <br/><br/>

    <label>Password</label>
    <input type="password" name="password" required>
    <br/><br/>
    
    <input type="submit" value="Login" />

    <p><a href="{% url 'user_auth:register' %}"
        class="text-primary fw-bold">Sign Up</a></p>

</form>

fae_paths/user_auth/templates/authentication/register.html
<h3>Register here</h3>
<hr>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Register</button>
</form>

fae_paths/user_auth/templates/authentication/user.html
<h1> Welcome, {{username}} </h1>
<p> Your password is {{password}} </p>